<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Base link parameters -->
    <xacro:property name="base_length"  value=".9"/>
    <xacro:property name="base_width"   value=".61"/>
    <xacro:property name="base_height"  value=".035"/>
    <xacro:property name="base_mass"    value="20"/>

    <xacro:macro name="base_link" params="prefix">

        <link name="${prefix}_base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="dark_gray"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${base_mass}"/>
                <cuboid_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
            </inertial>
        </link>
        
        <!-- Kinect mounting -->
        <xacro:property name="kinect_mounting_x" value="0.06"/>
        <xacro:property name="kinect_mounting_y" value="0.06"/>
        <xacro:property name="kinect_mounting_z" value="0.15"/>
        <xacro:property name="kinect_mounting_mass" value="0.0002"/>
        
        <joint name="${prefix}_kinect_mounting_joint" type="fixed">
            <origin xyz="-0.1 0 ${base_height/2 + kinect_mounting_z/2}" rpy="0 0 0" />
            <parent link="${prefix}_base_link"/>
            <child link="${prefix}_kinect_mounting"/>
        </joint>

        <link name="${prefix}_kinect_mounting">
            <visual>
                <geometry>
                    <box size="${kinect_mounting_x} ${kinect_mounting_y} ${kinect_mounting_z}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name="gray"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${kinect_mounting_x} ${kinect_mounting_y} ${kinect_mounting_z}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0"/>
                <cuboid_inertia m="${kinect_mounting_mass}" x="${kinect_mounting_x}" y="${kinect_mounting_y}" z="${kinect_mounting_z}"/>
            </inertial>
        </link>

    </xacro:macro>

</robot>